name: odoo

services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $default_pwd
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /DATA/AppData/$AppID/postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - postgres
    expose:
      - 8069
    environment:
      HOST: postgres
      USER: postgres
      PASSWORD: $default_pwd
    volumes:
      - /DATA/AppData/$AppID/web-data:/var/lib/odoo
      - /DATA/AppData/$AppID/addons:/mnt/extra-addons
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main: odoo
  webui_port: 8069
  category: Business
  author: CasaOS Team
  developer: Odoo S.A.
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Odoo/icon.png
  title:
    en_us: Odoo
  tagline:
    en_us: Business management suite
  index: /