listen: :443

# Using TLS with self-signed certificates
tls:
  cert: /acme/cert.pem
  key: /acme/key.pem
  sniGuard: disable

auth:
  type: password
  password: $PWD

# Maximum upload and download speeds per client
bandwidth:
  up: 50 mbps
  down: 100 mbps

# Logging level (debug, info, warn, error)
logging:
  level: info