name: seafile

services:
  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    user: $PUID:$PGID
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/shared:/shared
    environment:
      DB_HOST: 127.0.0.1
      DB_ROOT_PASSWD: $default_pwd
      TIME_ZONE: $TZ
      SEAFILE_ADMIN_EMAIL: admin@seafile.local
      SEAFILE_ADMIN_PASSWORD: $default_pwd
      SEAFILE_SERVER_LETSENCRYPT: false
      SEAFILE_SERVER_HOSTNAME: $domain
      PUID: $PUID
      PGID: $PGID
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.8'

x-casaos:
  architectures:
    - amd64
    - arm64
  main: seafile
  description:
    en_us: "Seafile is an open source cloud storage system with privacy protection and teamwork features. Built-in database for easy deployment."
    ko_kr: "Seafile은 프라이버시 보호와 팀워크 기능을 갖춘 오픈소스 클라우드 스토리지 시스템입니다. 내장 데이터베이스로 쉬운 배포가 가능합니다."
  developer: Seafile Ltd.
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Seafile/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Seafile/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Seafile/screenshot-2.png
  tagline:
    en_us: "Fast, secure, and private cloud storage with file sync"
    ko_kr: "빠르고 안전한 프라이빗 클라우드 스토리지와 파일 동기화"
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Seafile/thumbnail.png
  title:
    en_us: Seafile
    ko_kr: Seafile
  tips:
    before_install:
      en_us: |
        **Default Admin Account**
        
        | Username | Password |
        |----------|----------|
        | admin@seafile.local | `$default_pwd` |
        
        **Features:**
        - Fast file synchronization with delta sync
        - Client-side encryption support
        - Desktop and mobile apps available
        - Built-in database for easy setup
        
        **After installation:**
        1. Wait 2-3 minutes for initial setup to complete
        2. Access Seafile via the web interface
        3. Login with the admin account above
        4. Download desktop client from [https://seafile.com/download/](https://seafile.com/download/)
      ko_kr: |
        **기본 관리자 계정**
        
        | 사용자명 | 비밀번호 |
        |----------|----------|
        | admin@seafile.local | `$default_pwd` |
        
        **주요 기능:**
        - 델타 동기화를 통한 빠른 파일 동기화
        - 클라이언트 측 암호화 지원
        - 데스크톱 및 모바일 앱 지원
        - 내장 데이터베이스로 쉬운 설정
        
        **설치 후:**
        1. 초기 설정 완료까지 2-3분 대기
        2. 웹 인터페이스로 Seafile 접속
        3. 위 관리자 계정으로 로그인
        4. [https://seafile.com/download/](https://seafile.com/download/)에서 데스크톱 클라이언트 다운로드
  category: Cloud
  port_map: "80"
  scheme: https
  webui_port: 80
  index: /