name: libreoffice

services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    environment:
      - username=admin
      - password=admin
      - extra_params=--o:ssl.enable=false
      - aliasgroup1=http://localhost:9980
    cap_add:
      - MKNOD
    ports:
      - "9980:9980"
    volumes:
      - /DATA/AppData/$AppID/config:/etc/loolwsd
      - /DATA/AppData/$AppID/data:/var/lib/lool
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: collabora
  author: UgEff
  category: Office
  description:
    en_us: LibreOffice Online - Edit documents, spreadsheets and presentations in your browser
  title:
    en_us: LibreOffice Online
  port_map: "9980"
  volumes:
    - /DATA/AppData/$AppID/config
    - /DATA/AppData/$AppID/data