name: pdfeditor

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    environment:
      - JWT_ENABLED=false
      - GENERATE_DEFAULT_FONTS=true
      # Configuration de l'URL racine
      - ROOT_URL=http://localhost:8080
      - APP_PROTOCOL=http
      - APP_HOST=localhost
      - APP_PORT=8080
      # Configuration des services internes
      - DOCSERVICE_INTERNAL_PORT=8000
      - CONVERTER_INTERNAL_PORT=8001
      # Configuration des ressources
      - NODE_MAX_MEMORY=4096
      - NGINX_MAX_WORKER_CONNECTIONS=4096
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/$AppID/data:/var/www/onlyoffice/Data
      - /DATA/AppData/$AppID/logs:/var/log/onlyoffice
      - /DATA/AppData/$AppID/fonts:/usr/share/fonts/truetype/custom  # Pour les polices personnalisées
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: onlyoffice
  author: UgEff
  category: Office
  description:
    en_us: OnlyOffice Document Server - Professional document editor and converter
  title:
    en_us: Document Converter & Editor
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/data
    - /DATA/AppData/$AppID/logs
    - /DATA/AppData/$AppID/fonts