name: pdfeditor

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    environment:
      - JWT_ENABLED=false
      - GENERATE_DEFAULT_FONTS=true
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_HOST=localhost
      - AMQP_PORT=5672
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/$AppID/data:/var/www/onlyoffice/Data
      - /DATA/AppData/$AppID/logs:/var/log/onlyoffice
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: onlyoffice
  author: UgEff
  category: Office
  description:
    en_us: OnlyOffice Document Server - Professional online editor for PDF and Office documents
  title:
    en_us: Document Converter & Editor
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/data
    - /DATA/AppData/$AppID/logs