name: pdfeditor

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    environment:
      - JWT_ENABLED=false
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/$AppID/logs:/var/log/onlyoffice
      - /DATA/AppData/$AppID/data:/var/www/onlyoffice/Data
      - /DATA/AppData/$AppID/lib:/var/lib/onlyoffice
      - /DATA/AppData/$AppID/db:/var/lib/postgresql
      - /DATA/AppData/$AppID/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: onlyoffice
  author: UgEff
  category: Office
  description:
    en_us: OnlyOffice Document Server - Professional online editor for PDF and Office documents
  title:
    en_us: PDF Editor
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/logs
    - /DATA/AppData/$AppID/data
    - /DATA/AppData/$AppID/lib
    - /DATA/AppData/$AppID/db
    - /DATA/AppData/$AppID/cache