name: gotenberg

services:
  gotenberg:
    image: gotenberg/gotenberg:7.10
    container_name: gotenberg
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DISABLE_GOOGLE_CHROME=1
    volumes:
      - /DATA/AppData/$AppID/data:/data
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: gotenberg
  author: UgEff
  category: Office
  description:
    en_us: A Docker-powered stateless API for PDF files - Convert, Merge, and manipulate PDFs
  title:
    en_us: Gotenberg PDF
  port_map: "3000"
  volumes:
    - /DATA/AppData/$AppID/data
