name: pdfarranger

services:
  pdfarranger:
    image: jeromerobert/pdfarranger-docker-ci:latest
    container_name: pdfarranger
    restart: unless-stopped
    environment:
      - DISPLAY=:0
    volumes:
      - /DATA/AppData/$AppID/config:/home/user/.config
      - /DATA/AppData/$AppID/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: pdfarranger
  author: UgEff
  category: Office
  description:
    en_us: Simple application for PDF file merging, splitting, and reordering/rotating PDF pages
  title:
    en_us: PDF Arranger
  port_map: ""
  volumes:
    - /DATA/AppData/$AppID/config
    - /DATA/AppData/$AppID/data
