name: stirling-pdf

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /DATA/AppData/$AppID/data:/data
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - ALLOW_HTTP=true
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: stirling-pdf
  author: UgEff
  category: Office
  description:
    en_us: Powerful PDF manipulation tool with web interface
  title:
    en_us: Stirling PDF
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/data
