name: pdfarranger

services:
  pdfarranger:
    image: lscr.io/linuxserver/pdfarranger:latest
    container_name: pdfarranger
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/data:/data
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: pdfarranger
  author: UgEff
  category: Office
  description:
    en_us: Simple application for PDF file merging, splitting, and reordering/rotating PDF pages
  title:
    en_us: PDF Arranger
  port_map: "3000"
  volumes:
    - /DATA/AppData/$AppID/config
    - /DATA/AppData/$AppID/data
