name: stirling-pdf

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8989:8080"
    volumes:
      - /DATA/AppData/$AppID/config:/configs
      - /DATA/AppData/$AppID/data:/usr/share/tesseract-ocr/4.00/tessdata
      - /DATA/AppData/$AppID/logs:/logs
    networks:
      pcs: null
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - BASE_URL=/
      - ALLOW_HTTP=true
      - SYSTEM_DEFAULTLOCALE=fr-FR
      - SECURITY_ENABLELOGIN=false
      - ENDPOINTS_TOREMOVE=[]
      - SYSTEM_TESSDATADIR=/usr/share/tesseract-ocr/4.00/tessdata
      - LOGGING_CONFIG=classpath:logback-spring.xml
      - SPRING_PROFILES_ACTIVE=prod
    user: "1000:1000"

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: stirling-pdf
  author: UgEff
  category: Office
  description:
    en_us: Powerful PDF manipulation tool - Split, merge, convert, and more
  title:
    en_us: Stirling PDF
  port_map: "8989"
  volumes:
    - /DATA/AppData/$AppID/config
    - /DATA/AppData/$AppID/data    - /DATA/AppData/$AppID/logs
