name: stirling-pdf

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /DATA/AppData/$AppID/config:/configs
      - /DATA/AppData/$AppID/data:/usr/share/tesseract-ocr/4.00/tessdata
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: stirling-pdf
  author: UgEff
  category: Office
  description:
    en_us: Powerful PDF manipulation tool - Split, merge, convert, and more
  title:
    en_us: Stirling PDF
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/config
    - /DATA/AppData/$AppID/data