name: pdftools

services:
  pdf-tools:
    image: gotenberg/gotenberg:8
    container_name: pdf-tools
    restart: unless-stopped
    environment:
      - DISABLE_GOOGLE_CHROME=0
    ports:
      - "3000:3000"
    volumes:
      - /DATA/AppData/$AppID/storage:/storage
      - /DATA/AppData/$AppID/output:/output
    networks:
      pcs: null

  pdf-interface:
    image: pdfmix/pdfmix:latest
    container_name: pdf-interface
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/$AppID/storage:/storage
      - /DATA/AppData/$AppID/output:/output
    depends_on:
      - pdf-tools
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: pdf-interface
  author: UgEff
  category: Office
  description:
    en_us: PDF Tools - Powerful PDF manipulation suite
  title:
    en_us: PDF Tools
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/storage
    - /DATA/AppData/$AppID/output