name: rocketchat

services:
  mongodb:
    image: mongo:4.2
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - /DATA/AppData/$AppID/mongodb:/data/db
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.5.0
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      ROOT_URL: http://localhost:80
      PORT: 80
      ADMIN_USERNAME: admin
      ADMIN_PASS: $default_pwd
      ADMIN_EMAIL: admin@localhost
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/uploads:/app/uploads
      - /DATA/AppData/$AppID/data:/app/data
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

x-casaos:
    architectures:
        - amd64
        - arm64
    main: rocketchat
    author: CasaOS Team
    category: Communication
    description:
        en_us: Rocket.Chat is an open-source team communication platform. It provides chat, video conferencing, file sharing and many other communication features for teams.
    developer: Rocket.Chat Technologies Corp.
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RocketChat/icon.png
    tagline:
        en_us: Open-source team communication platform
    title:
        en_us: Rocket.Chat
    tips:
        before_install:
            en_us: |
                Default Account
                | Username | Password |
                | -------- | -------- |
                | `admin`  | `$default_pwd` |
    index: /
    port_map: "80"