name: rocketchat-simple

services:
  mongodb:
    image: mongo:6.0
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - /DATA/AppData/$AppID/mongodb:/data/db
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.5.0
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      ROOT_URL: http://localhost:80
      PORT: 80
      ADMIN_USERNAME: admin
      ADMIN_PASS: $default_pwd
      ADMIN_EMAIL: admin@localhost
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/uploads:/app/uploads
      - /DATA/AppData/$AppID/data:/app/data
    depends_on:
      - mongodb
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main: rocketchat
  author: Yundera Team
  category: Utilities
  description:
    en_us: Rocket.Chat team communication platform with MongoDB 6.0 for older CPU compatibility
  developer: Rocket.Chat Technologies Corp.
  tagline:
    en_us: Team communication platform compatible with older hardware
  title:
    en_us: Rocket.Chat
  tips:
    before_install:
      en_us: |
        Default login: admin / (auto-generated password)
        Compatible with older CPUs - no AVX requirement
  index: /
  webui_port: 80