name: rocketchat

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.5.0
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    environment:
      # 외부 MongoDB 연결 (예시 - 실제 MongoDB URL로 변경 필요)
      MONGO_URL: mongodb://your-mongodb-host:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://your-mongodb-host:27017/local
      ROOT_URL: https://$domain/
      PORT: 80
      ADMIN_USERNAME: admin
      ADMIN_PASS: $default_pwd
      ADMIN_EMAIL: admin@$domain
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/uploads:/app/uploads
      - /DATA/AppData/$AppID/data:/app/data
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main: rocketchat
  author: Yundera Team
  category: Communication
  description:
    en_us: Rocket.Chat is an open-source team communication platform. This version requires an external MongoDB database.
    ko_kr: Rocket.Chat은 오픈소스 팀 커뮤니케이션 플랫폼입니다. 이 버전은 외부 MongoDB 데이터베이스가 필요합니다.
  developer: Rocket.Chat Technologies Corp.
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Rocket.Chat/icon.png
  tagline:
    en_us: Lightweight Rocket.Chat deployment with external MongoDB
    ko_kr: 외부 MongoDB를 사용하는 경량 Rocket.Chat 배포
  title:
    en_us: Rocket.Chat (External DB)
    ko_kr: Rocket.Chat (외부 DB)
  tips:
    before_install:
      en_us: |
        **Requirements:**
        - External MongoDB 6.0+ with replica set enabled
        - Update MONGO_URL and MONGO_OPLOG_URL in the compose file
        
        **Default Account:**
        | Username | Password |
        |----------|----------|
        | `admin`  | `$default_pwd` |
      ko_kr: |
        **요구사항:**
        - 복제본 세트가 활성화된 외부 MongoDB 6.0+ 필요
        - compose 파일에서 MONGO_URL과 MONGO_OPLOG_URL 업데이트 필요
        
        **기본 계정:**
        | 사용자명 | 비밀번호 |
        |----------|----------|
        | `admin`  | `$default_pwd` |
  index: /
  webui_port: 80