# Nom du projet Docker Compose
name: pgadmin

services:
  # Service pour l'interface web pgAdmin
  pgadmin:
    # Image Docker officielle de pgAdmin4
    image: dpage/pgadmin4:latest
    # Nom du conteneur
    container_name: pgadmin
    # Redémarrage automatique sauf si arrêté manuellement
    restart: unless-stopped
    # Configuration correcte de l'utilisateur (user ID:group ID)
    user: "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com     # Email de connexion
      - PGADMIN_DEFAULT_PASSWORD=admin              # Mot de passe de connexion
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
    # Configuration du port
    ports:
      - "8080:80"   # Format simplifié pour le mappage de port
    # Configuration des volumes pour la persistance des données
    volumes:
      - /DATA/AppData/$AppID/pgadmin:/var/lib/pgadmin
    # Dépendance avec attente que PostgreSQL soit prêt
    depends_on:
      postgres:
        condition: service_healthy
    # Configuration réseau
    networks:
      - pcs

  # Service pour le serveur PostgreSQL
  postgres:
    image: postgres:latest                         
    container_name: postgres
    restart: unless-stopped
    # Variables d'environnement pour PostgreSQL
    environment:
      - POSTGRES_USER=admin                        
      - POSTGRES_PASSWORD=admin                     
      - POSTGRES_DB=postgres
    # Volume pour les données PostgreSQL
    volumes:
      - /DATA/AppData/$AppID/postgres:/var/lib/postgresql/data
    # Port exposé pour accès externe si nécessaire
    ports:
      - "5432:5432"  # Accessible depuis l'extérieur
    # Vérification de la santé du service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pcs

# Définition du réseau partagé
networks:
  pcs:
    external: true  # Utilise un réseau existant au lieu d'en créer un nouveau
    name: pcs

# Configuration spécifique à CasaOS
x-casaos:
  architectures:
    - amd64
    - arm64
  main: pgadmin
  author: UgEff
  category: Database
  description:
    en_us: pgAdmin - A web-based database management tool for PostgreSQL with integrated PostgreSQL server
  developer: PostgreSQL
  tagline:
    en_us: Manage PostgreSQL databases easily with pgAdmin
  title:
    en_us: PgAdmin + PostgreSQL
  index: /
  port_map: "8080"
  volumes:
    - /DATA/AppData/$AppID/pgadmin
    - /DATA/AppData/$AppID/postgres