version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - /DATA/AppData/postgres/data:/var/lib/postgresql/data  
    expose:
      - 5432  
    networks:
      - pcs

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - target: 80  
        published: "8000"  
        protocol: tcp
    depends_on:
      - postgres
    networks:
      - pcs

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  main: pgadmin 
  author: UgEff
  category: Database
  description:
    en_us: pgAdmin - A web-based database management tool for PostgreSQL
  developer: PostgreSQL
  icon: https://static-00.iconduck.com/assets.00/postgresql-icon-1987x2048-v2fkmdaw.png
  screenshot_link:
    - https://www.pgadmin.org/static/images/screenshots/pgadmin4-dashboard.png
    - https://github.com/UgEff/AppStore/blob/BiApp/Apps/PgAdmin_PostgreSQL/Capture%20d'%C3%A9cran%202025-03-04%20083128.png
    - https://github.com/UgEff/AppStore/blob/BiApp/Apps/PgAdmin_PostgreSQL/Capture%20d%E2%80%99%C3%A9cran%202025-03-04%20083354.png
    - https://github.com/UgEff/AppStore/blob/BiApp/Apps/PgAdmin_PostgreSQL/Capture%20d%E2%80%99%C3%A9cran%202025-03-04%20083613.png
  tagline:
    en_us: Manage PostgreSQL databases easily with pgAdmin
  title:
    en_us: pgAdmin
  index: /
  port_map: "8000"
