name: PgAdmin

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - type: bind
        source: /DATA/AppData/postgres/data
        target: /var/lib/postgresql/data
    expose:
      - 5432  
    networks:
      - pgadmin_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - target: 80  
        published: "8000"  
        protocol: tcp
    depends_on:
      - postgres:
        condition: service_healthy
    volumes:
      - type: bind
        source: /DATA/AppData/pgadmin
        target: /var/lib/pgadmin
    networks:
      - pgadmin_network

networks:
  pgadmin_network:
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  main: pgadmin
  author: UgEff
  category: Database
  description:
    en_us: pgAdmin - A web-based database management tool for PostgreSQL with integrated PostgreSQL server
  developer: PostgreSQL
  tagline:
    en_us: Manage PostgreSQL databases easily with pgAdmin
  title:
    en_us: PgAdmin + PostgreSQL
  index: /
  port_map: "8000"
  store:
    app_name: PgAdmin_PostgreSQL
    database: postgres
  volumes:
    - /DATA/AppData/postgres/data
    - /DATA/AppData/pgadmin
