name: filebrowser

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    user: $PUID:$PGID
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/database:/database
      - /DATA/AppData/$AppID/config:/config
      - /DATA/Documents:/srv/Documents
      - /DATA/Downloads:/srv/Downloads
      - /DATA/Media:/srv/Media
      - /DATA/Gallery:/srv/Gallery
      - /DATA:/srv/DATA
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'

x-casaos:
  architectures:
    - amd64
    - arm64
  main: filebrowser
  author: CasaOS Team
  category: Cloud
  description:
    en_us: "FileBrowser provides a file managing interface like Google Drive. Upload, download, preview, edit and manage your files through a beautiful web interface with drag & drop support."
    ko_kr: "FileBrowser는 Google Drive 같은 파일 관리 인터페이스를 제공합니다. 드래그 앤 드롭과 아름다운 웹 인터페이스로 파일을 업로드, 다운로드, 미리보기, 편집할 수 있습니다."
  developer: FileBrowser Team
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/icon.png
  tagline:
    en_us: "Web File Manager - Upload files like Google Drive"
    ko_kr: "웹 파일 매니저 - Google Drive처럼 파일 업로드"
  title:
    en_us: FileBrowser
    ko_kr: FileBrowser
  tips:
    before_install:
      en_us: |
        **Perfect Google Drive Alternative**
        
        **Default Login:**
        | Username | Password |
        |----------|----------|
        | admin | admin |
        
        **Features:**
        - **Drag & Drop Upload** - Just like Google Drive!
        - **File Preview** - Images, videos, documents
        - **File Editing** - Text files, code files
        - **Download & Upload** - Easy file management
        - **User Management** - Multiple users support
        - **File Sharing** - Share files with links
        
        **Accessible Folders:**
        - `/srv/Documents` → Your Documents
        - `/srv/Downloads` → Your Downloads
        - `/srv/Media` → Your Media files
        - `/srv/Gallery` → Your Photos
        - `/srv/DATA` → Full CasaOS data access
        
        **After installation:**
        1. Access via web interface
        2. Login with admin/admin
        3. **Change password immediately!**
        4. Start uploading files like Google Drive!
      ko_kr: |
        **완벽한 Google Drive 대체재**
        
        **기본 로그인:**
        | 사용자명 | 비밀번호 |
        |----------|----------|
        | admin | admin |
        
        **주요 기능:**
        - **드래그 앤 드롭 업로드** - Google Drive처럼!
        - **파일 미리보기** - 이미지, 비디오, 문서
        - **파일 편집** - 텍스트 파일, 코드 파일
        - **다운로드 & 업로드** - 쉬운 파일 관리
        - **사용자 관리** - 여러 사용자 지원
        - **파일 공유** - 링크로 파일 공유
        
        **접근 가능한 폴더:**
        - `/srv/Documents` → 문서 폴더
        - `/srv/Downloads` → 다운로드 폴더
        - `/srv/Media` → 미디어 파일
        - `/srv/Gallery` → 사진 폴더
        - `/srv/DATA` → 전체 CasaOS 데이터 접근
        
        **설치 후:**
        1. 웹 인터페이스 접속
        2. admin/admin으로 로그인
        3. **즉시 비밀번호 변경!**
        4. Google Drive처럼 파일 업로드 시작!
  index: /
  webui_port: 80