name: syncthing

services:
  syncthing:
    image: linuxserver/syncthing:latest
    user: $PUID:$PGID
    expose:
      - 8384
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/Documents:/data1
      - /DATA/Downloads:/data2
      - /DATA/Media:/data3
      - /DATA/Gallery:/data4
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

x-casaos:
  architectures:
    - amd64
    - arm64
  main: syncthing
  author: CasaOS Team
  category: Cloud
  description:
    en_us: "Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers and mobile devices in real time, safely protected from prying eyes. Your data is your data alone."
    ko_kr: "Syncthing은 연속 파일 동기화 프로그램입니다. 둘 이상의 컴퓨터와 모바일 기기 간에 실시간으로 파일을 동기화하며, 프라이버시가 안전하게 보호됩니다."
  developer: Syncthing Foundation
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Syncthing/icon.png
  tagline:
    en_us: "Decentralized file synchronization - no cloud needed"
    ko_kr: "분산형 파일 동기화 - 클라우드 불필요"
  title:
    en_us: Syncthing
    ko_kr: Syncthing
  tips:
    before_install:
      en_us: |
        **Perfect Google Drive Alternative**
        
        **Features:**
        - **No Cloud Required**: Direct device-to-device sync
        - **Real-time Sync**: Files sync instantly between devices
        - **Cross-Platform**: Windows, Mac, Linux, Android, iOS
        - **Private & Secure**: End-to-end encrypted, no third-party servers
        - **Selective Sync**: Choose which folders to sync
        
        **Pre-configured Folders:**
        - `/data1` → Documents folder
        - `/data2` → Downloads folder  
        - `/data3` → Media folder
        - `/data4` → Gallery folder
        
        **After installation:**
        1. Access web interface via CasaOS
        2. Note your Device ID
        3. Download Syncthing apps: [https://syncthing.net/downloads/](https://syncthing.net/downloads/)
        4. Add devices and share folders
        5. Start syncing!
        
        **Mobile Apps:** Available on Google Play and App Store
      ko_kr: |
        **완벽한 Google Drive 대체재**
        
        **주요 기능:**
        - **클라우드 불필요**: 기기 간 직접 동기화
        - **실시간 동기화**: 파일이 즉시 동기화됨
        - **크로스 플랫폼**: Windows, Mac, Linux, Android, iOS
        - **비공개 & 보안**: 엔드투엔드 암호화, 제3자 서버 없음
        - **선택적 동기화**: 동기화할 폴더 선택 가능
        
        **사전 설정된 폴더:**
        - `/data1` → 문서 폴더
        - `/data2` → 다운로드 폴더
        - `/data3` → 미디어 폴더
        - `/data4` → 갤러리 폴더
        
        **설치 후:**
        1. CasaOS를 통해 웹 인터페이스 접속
        2. 장치 ID 확인
        3. Syncthing 앱 다운로드: [https://syncthing.net/downloads/](https://syncthing.net/downloads/)
        4. 장치 추가 및 폴더 공유
        5. 동기화 시작!
        
        **모바일 앱:** Google Play와 App Store에서 사용 가능
  index: /
  port_map: "8384"
  webui_port: 8384