# Nom du projet Docker Compose
name: mongodb

version: '3'

services:
  # Service pour le serveur MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /DATA/AppData/$AppID/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - pcs
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Service pour l'interface web Mongo-Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_BASEURL: /
      VCAP_APP_PORT: 8081
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - pcs

# Définition du réseau partagé
networks:
  pcs:
    external: true

# Configuration spécifique à CasaOS
x-casaos:
  architectures:
    - amd64
    - arm64
  main: mongo-express
  title:
    en_us: MongoDB + Mongo Express
  icon: https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/IconMangoDB.png
  tagline:
    en_us: MongoDB database with web interface
  description:
    en_us: MongoDB database server with Mongo Express web management interface
  category: Database
  port_map: "8081"
  author: UgEff
  screenshot_link:
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/screen1.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/screen2.jpg
  volumes:
    - /DATA/AppData/$AppID/mongodb
