# Nom du projet Docker Compose
name: mongodb

services:
  # Service pour le serveur MongoDB
  mongodb:
    image: mongo:latest                            # Image officielle MongoDB
    container_name: mongodb                         # Nom du conteneur
    restart: unless-stopped                         # Redémarrage automatique
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin           # Utilisateur root MongoDB
      - MONGO_INITDB_ROOT_PASSWORD=admin           # Mot de passe root MongoDB
    volumes:
      - /DATA/AppData/$AppID/mongodb:/data/db
    expose:
      - 27017                                      # Port MongoDB (interne uniquement)
    # Vérification de la santé du service
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pcs: null                                    # Connexion au réseau partagé

  # Service pour l'interface web Mongo-Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    volumes:
      - /DATA/AppData/$AppID/mongo-express:/data
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      pcs: null

# Définition du réseau partagé
networks:
  pcs:
    name: pcs

# Configuration spécifique à CasaOS
x-casaos:
  architectures:
    - amd64
    - arm64
  main: mongo-express
  author: UgEff
  category: Database
  description:
    en_us: Mongo-Express - A web-based interface to manage MongoDB easily.
  title:
    en_us: MongoDB + Mongo Express
  port_map: "8081"
  volumes:
    - /DATA/AppData/$AppID/mongo-express
    - /DATA/AppData/$AppID/mongodb