# Nom du projet Docker Compose
name: mongodb

services:
  # Service pour le serveur MongoDB
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /DATA/AppData/$AppID/data:/data/db
    networks:
      - mongodb_network

  # Service pour l'interface web Mongo-Express
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8888:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - mongodb_network
    depends_on:
      - mongodb

# Définition du réseau partagé
networks:
  mongodb_network:
    driver: bridge

# Configuration spécifique à CasaOS
x-casaos:
  architectures:
    - amd64
    - arm64
  main: mongo-express
  author: UgEff
  category: Database
  description:
    en_us: MongoDB database with web interface Mongo Express
  title:
    en_us: MongoDB + Mongo Express
  icon: https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/IconMangoDB.png
  screenshot_link:
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/screen1.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/MangoDB_ExpressDB/screen2.jpg
  port_map: "8888"
  volumes:
    - /DATA/AppData/$AppID/data